<?php

class Crumblez_Model_Units extends Reusable_Model_Object_MyPresistable_Abstract 
{
	public static function getUnitData()
	{
		return array(
			'militia' => array(
    			'attack_type' => 'pierce',
    			'attack' => '2',
    			'def_hack' => '6',
    			'def_pierce' => '8',
    			'def_distance' => '4',
    			'booty' => '',
    			'speed' => '0',
    			'population' => '0',
    			'build_time' => '1',
    			'god_id' => '',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 0,
    				'stone' => 0,
    				'iron' => 0,
    				'favor' => 0,
    			)
    		),
    		'sword' => array(
    			'attack_type' => 'hack',
    			'attack' => '5',
    			'def_hack' => '14',
    			'def_pierce' => '8',
    			'def_distance' => '30',
    			'booty' => '16',
    			'speed' => '16',
    			'population' => '1',
    			'build_time' => '1080',
    			'god_id' => '',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 95,
    				'stone' => 0,
    				'iron' => 85,
    				'favor' => 0,
    			)
    		),
    		'slinger' => array(
    			'attack_type' => 'distance',
    			'attack' => '23',
    			'def_hack' => '7',
    			'def_pierce' => '8',
    			'def_distance' => '2',
    			'booty' => '8',
    			'speed' => '28',
    			'population' => '1',
    			'build_time' => '1200',
    			'god_id' => '',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 55,
    				'stone' => 100,
    				'iron' => 40,
    				'favor' => 0,
    			)
    		),
    		'archer' => array(
    			'attack_type' => 'distance',
    			'attack' => '8',
    			'def_hack' => '6',
    			'def_pierce' => '25',
    			'def_distance' => '12',
    			'booty' => '24',
    			'speed' => '24',
    			'population' => '1',
    			'build_time' => '1140',
    			'god_id' => '',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 120,
    				'stone' => 0,
    				'iron' => 75,
    				'favor' => 0,
    			)
    		),
    		'hoplite' => array(
    			'attack_type' => 'pierce',
    			'attack' => '16',
    			'def_hack' => '18',
    			'def_pierce' => '12',
    			'def_distance' => '7',
    			'booty' => '8',
    			'speed' => '12',
    			'population' => '1',
    			'build_time' => '1380',
    			'god_id' => '',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 0,
    				'stone' => 75,
    				'iron' => 150,
    				'favor' => 0,
    			)
    		),
    		'rider' => array(
    			'attack_type' => 'hack',
    			'attack' => '55',
    			'def_hack' => '18',
    			'def_pierce' => '1',
    			'def_distance' => '24',
    			'booty' => '72',
    			'speed' => '44',
    			'population' => '3',
    			'build_time' => '4320',
    			'god_id' => '',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 240,
    				'stone' => 120,
    				'iron' => 360,
    				'favor' => 0,
    			)
    		),
    		'chariot' => array(
    			'attack_type' => 'pierce',
    			'attack' => '56',
    			'def_hack' => '76',
    			'def_pierce' => '16',
    			'def_distance' => '56',
    			'booty' => '64',
    			'speed' => '36',
    			'population' => '4',
    			'build_time' => '5760',
    			'god_id' => '',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 200,
    				'stone' => 440,
    				'iron' => 320,
    				'favor' => 0,
    			)
    		),
    		'catapult' => array(
    			'attack_type' => 'distance',
    			'attack' => '100',
    			'def_hack' => '30',
    			'def_pierce' => '30',
    			'def_distance' => '30',
    			'booty' => '400',
    			'speed' => '2',
    			'population' => '15',
    			'build_time' => '21600',
    			'god_id' => '',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 1200,
    				'stone' => 1200,
    				'iron' => 1200,
    				'favor' => 0,
    			)
    		),
    		'minotaur' => array(
    			'attack_type' => 'hack',
    			'attack' => '420',
    			'def_hack' => '675',
    			'def_pierce' => '300',
    			'def_distance' => '560',
    			'booty' => '480',
    			'speed' => '20',
    			'population' => '30',
    			'build_time' => '16200',
    			'god_id' => 'zeus',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 1400,
    				'stone' => 600,
    				'iron' => 3100,
    				'favor' => 202,
    			)
    		),
    		'manticore' => array(
    			'attack_type' => 'pierce',
    			'attack' => '945',
    			'def_hack' => '170',
    			'def_pierce' => '225',
    			'def_distance' => '505',
    			'booty' => '360',
    			'speed' => '44',
    			'population' => '45',
    			'build_time' => '32400',
    			'god_id' => 'zeus',
    			'type' => 'land',
    			'flying' => '1',
    			'resources' => array(
    				'wood' => 4400,
    				'stone' => 3000,
    				'iron' => 3400,
    				'favor' => 405,
    			)
    		),
    		'zyklop' => array(
    			'attack_type' => 'distance',
    			'attack' => '756',
    			'def_hack' => '945',
    			'def_pierce' => '10',
    			'def_distance' => '1310',
    			'booty' => '320',
    			'speed' => '16',
    			'population' => '40',
    			'build_time' => '28680',
    			'god_id' => 'poseidon',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 2000,
    				'stone' => 4200,
    				'iron' => 3360,
    				'favor' => 360,
    			)
    		),
    		'harpy' => array(
    			'attack_type' => 'hack',
    			'attack' => '266',
    			'def_hack' => '105',
    			'def_pierce' => '70',
    			'def_distance' => '1',
    			'booty' => '340',
    			'speed' => '50',
    			'population' => '14',
    			'build_time' => '10080',
    			'god_id' => 'hera',
    			'type' => 'land',
    			'flying' => '1',
    			'resources' => array(
    				'wood' => 1600,
    				'stone' => 400,
    				'iron' => 1360,
    				'favor' => 130,
    			)
    		),
    		'medusa' => array(
    			'attack_type' => 'pierce',
    			'attack' => '425',
    			'def_hack' => '625',
    			'def_pierce' => '435',
    			'def_distance' => '375',
    			'booty' => '400',
    			'speed' => '12',
    			'population' => '18',
    			'build_time' => '22500',
    			'god_id' => 'hera',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 1500,
    				'stone' => 3800,
    				'iron' => 2200,
    				'favor' => 210,
    			)
    		),
    		'centaur' => array(
    			'attack_type' => 'distance',
    			'attack' => '156',
    			'def_hack' => '150',
    			'def_pierce' => '450',
    			'def_distance' => '60',
    			'booty' => '200',
    			'speed' => '36',
    			'population' => '12',
    			'build_time' => '8190',
    			'god_id' => 'athena',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 1740,
    				'stone' => 300,
    				'iron' => 700,
    				'favor' => 100,
    			)
    		),
    		'pegasus' => array(
    			'attack_type' => 'pierce',
    			'attack' => '100',
    			'def_hack' => '900',
    			'def_pierce' => '250',
    			'def_distance' => '300',
    			'booty' => '160',
    			'speed' => '70',
    			'population' => '20',
    			'build_time' => '14400',
    			'god_id' => 'athena',
    			'type' => 'land',
    			'flying' => '1',
    			'resources' => array(
    				'wood' => 2800,
    				'stone' => 360,
    				'iron' => 80,
    				'favor' => 180,
    			)
    		),
    		'cerberus' => array(
    			'attack_type' => 'hack',
    			'attack' => '210',
    			'def_hack' => '825',
    			'def_pierce' => '300',
    			'def_distance' => '1575',
    			'booty' => '240',
    			'speed' => '8',
    			'population' => '30',
    			'build_time' => '8400',
    			'god_id' => 'hades',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 1250,
    				'stone' => 1500,
    				'iron' => 3000,
    				'favor' => 230,
    			)
    		),
    		'fury' => array(
    			'attack_type' => 'distance',
    			'attack' => '1210',
    			'def_hack' => '688',
    			'def_pierce' => '688',
    			'def_distance' => '895',
    			'booty' => '440',
    			'speed' => '20',
    			'population' => '55',
    			'build_time' => '21600',
    			'god_id' => 'hades',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 2500,
    				'stone' => 5000,
    				'iron' => 5000,
    				'favor' => 480,
    			)
    		),
    		'griffin' => array(
    			'attack_type' => 'hack',
    			'attack' => '860',
    			'def_hack' => '240',
    			'def_pierce' => '270',
    			'def_distance' => '100',
    			'booty' => '350',
    			'speed' => '40',
    			'population' => '35',
    			'build_time' => '17100',
    			'god_id' => 'artemis',
    			'type' => 'land',
    			'flying' => '1',
    			'resources' => array(
    				'wood' => 3800,
    				'stone' => 1900,
    				'iron' => 4800,
    				'favor' => 250,
    			)
    		),
    		'calydonian_boar' => array(
    			'attack_type' => 'pierce',
    			'attack' => '250',
    			'def_hack' => '450',
    			'def_pierce' => '950',
    			'def_distance' => '100',
    			'booty' => '240',
    			'speed' => '32',
    			'population' => '20',
    			'build_time' => '7800',
    			'god_id' => 'artemis',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 2800,
    				'stone' => 1400,
    				'iron' => 1600,
    				'favor' => 110,
    			)
    		),
    		'godsent' => array(
    			'attack_type' => 'hack',
    			'attack' => '35',
    			'def_hack' => '20',
    			'def_pierce' => '20',
    			'def_distance' => '20',
    			'booty' => '5',
    			'speed' => '32',
    			'population' => '3',
    			'build_time' => '2100',
    			'god_id' => 'all',
    			'type' => 'land',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 0,
    				'stone' => 0,
    				'iron' => 0,
    				'favor' => 15,
    			)
    		),
    		'big_transporter' => array(
    			'attack_type' => '',
    			'attack' => '20',
    			'def_hack' => '',
    			'def_pierce' => '',
    			'def_distance' => '',
    			'booty' => '',
    			'speed' => '16',
    			'population' => '7',
    			'build_time' => '9600',
    			'god_id' => '',
    			'type' => 'naval',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 500,
    				'stone' => 500,
    				'iron' => 400,
    				'favor' => 0,
    			)
    		),
    		'bireme' => array(
    			'attack_type' => '',
    			'attack' => '24',
    			'def_hack' => '',
    			'def_pierce' => '',
    			'def_distance' => '',
    			'booty' => '',
    			'speed' => '30',
    			'population' => '8',
    			'build_time' => '9900',
    			'god_id' => '',
    			'type' => 'naval',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 800,
    				'stone' => 700,
    				'iron' => 180,
    				'favor' => 0,
    			)
    		),
    		'attack_ship' => array(
    			'attack_type' => '',
    			'attack' => '200',
    			'def_hack' => '',
    			'def_pierce' => '',
    			'def_distance' => '',
    			'booty' => '',
    			'speed' => '26',
    			'population' => '10',
    			'build_time' => '14400',
    			'god_id' => '',
    			'type' => 'naval',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 1300,
    				'stone' => 300,
    				'iron' => 800,
    				'favor' => 0,
    			)
    		),
    		'demolition_ship' => array(
    			'attack_type' => '',
    			'attack' => '20',
    			'def_hack' => '',
    			'def_pierce' => '',
    			'def_distance' => '',
    			'booty' => '',
    			'speed' => '10',
    			'population' => '8',
    			'build_time' => '4000',
    			'god_id' => '',
    			'type' => 'naval',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 500,
    				'stone' => 750,
    				'iron' => 150,
    				'favor' => 0,
    			)
    		),
    		'small_transporter' => array(
    			'attack_type' => '',
    			'attack' => '20',
    			'def_hack' => '',
    			'def_pierce' => '',
    			'def_distance' => '',
    			'booty' => '',
    			'speed' => '30',
    			'population' => '5',
    			'build_time' => '7200',
    			'god_id' => '',
    			'type' => 'naval',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 800,
    				'stone' => 0,
    				'iron' => 400,
    				'favor' => 0,
    			)
    		),
    		'trireme' => array(
    			'attack_type' => '',
    			'attack' => '180',
    			'def_hack' => '',
    			'def_pierce' => '',
    			'def_distance' => '',
    			'booty' => '',
    			'speed' => '18',
    			'population' => '16',
    			'build_time' => '14400',
    			'god_id' => '',
    			'type' => 'naval',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 2000,
    				'stone' => 1300,
    				'iron' => 900,
    				'favor' => 0,
    			)
    		),
    		'colonize_ship' => array(
    			'attack_type' => '',
    			'attack' => '0',
    			'def_hack' => '',
    			'def_pierce' => '',
    			'def_distance' => '',
    			'booty' => '',
    			'speed' => '6',
    			'population' => '170',
    			'build_time' => '64800',
    			'god_id' => '',
    			'type' => 'naval',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 10000,
    				'stone' => 10000,
    				'iron' => 10000,
    				'favor' => 0,
    			)
    		),
    		'sea_monster' => array(
    			'attack_type' => '',
    			'attack' => '1000',
    			'def_hack' => '',
    			'def_pierce' => '',
    			'def_distance' => '',
    			'booty' => '',
    			'speed' => '16',
    			'population' => '50',
    			'build_time' => '42000',
    			'god_id' => 'poseidon',
    			'type' => 'naval',
    			'flying' => '',
    			'resources' => array(
    				'wood' => 5400,
    				'stone' => 2800,
    				'iron' => 3800,
    				'favor' => 400,
    			)
    		),
			);
	}
	
}

?>