<h1><?php echo $this->Translate('Oih!');?></h1>
<?php echo $this->Translate('Meil tekkis väike viga');?><br />
<?php echo $this->Translate('Tehnilise taibuga patsipoistele on saadetud sõnum.');?><br />
<?php echo $this->Translate('Palun proovige mõne minuti pärast uuesti.');?><br />






<?php if ('development' == APPLICATION_ENV || $_GET['testime'] == 'appiappiappi'): ?>
    <h3>Exception information:</h3>
    <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>
    
    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
    </pre>
    
    <h3>Request Parameters:</h3>
    <pre><?php echo var_export($this->request->getParams(), true) ?>
    </pre>
    
    <h3>Session Parameters:</h3>
    <pre><?php echo var_export($_SESSION, true) ?>
    </pre>
<?php endif; ?>